# Generated by Django 5.2.4 on 2025-07-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
